# NumPy (Numerical Python)

 

What is NumPy?
***************
NumPy (Numerical Python) is a library for working with arrays and mathematical operations in Python. It provides support for large, multi-dimensional arrays and matrices, and is the foundation of most scientific computing in Python.

__Key Features of NumPy__
************************

1. Multi-dimensional arrays: NumPy arrays can have any number of dimensions, and can be indexed and sliced like Python lists.
2. Vectorized operations: NumPy provides a wide range of mathematical operations that can be applied to entire arrays at once, making it much faster than working with Python lists.
3. Broadcasting: NumPy arrays can be broadcasted to perform operations on arrays with different shapes and sizes.
4. Data types: NumPy arrays can have a variety of data types, including integers, floating-point numbers, and complex numbers.

__NumPy Data Types__
*******************
1. int8, int16, int32, int64: Signed integer types
2. uint8, uint16, uint32, uint64: Unsigned integer types
3. float16, float32, float64: Floating-point number types
4. complex64, complex128: Complex number types
5. bool: Boolean type
6. object: Object type (used for arrays of Python objects)

__NumPy Array Operations__
*******************************
1. Basic operations: +, -, *, /, **, etc.
1. <Element-wise operations:> np.sin(), np.cos(), np.exp(), etc.
1. Matrix operations: np.dot(), np.matmul(), np.linalg.inv(), etc.
1. Statistical operations: np.mean(), np.median(), np.std(), etc.
1. Indexing and slicing: arr[0], arr[0:5], arr[:, 0], etc.

__NumPy Functions__
***********************

1. np.array(): Create a NumPy array from a Python list or other iterable.
1. np.zeros(): Create a NumPy array filled with zeros.
1. np.ones(): Create a NumPy array filled with ones.
1. np.random.rand(): Create a NumPy array filled with random numbers.
1. np.linspace(): Create a NumPy array with evenly spaced values.
1. np.sort(): Sort a NumPy array.
1. np.reshape(): Reshape a NumPy array.

__NumPy Indexing and Slicing__
*********************
1. Basic indexing: arr[0], arr[1], etc.
1. Slice indexing: arr[0:5], arr[1:3], etc.
1. Multi-dimensional indexing: arr[0, 1], arr[1, 2], etc.
1. Boolean indexing: arr[arr > 0], arr[arr < 0], etc.

__Why use NumPy__
***********
1. Speed:Numpy aims to provide an array object that is up to 50x faster than traditional python lists.
1. Memory efficiency
1. Vectorized operations
1. Broadcasting
1. Interoperability
1. Scientific computing
1. Data analysis 


In [18]:
import numpy as np

In [5]:
arr = np.array([1,2,3])
print(arr,type(arr))

[1 2 3] <class 'numpy.ndarray'>


In [6]:
# Passing tuple
t = np.array((1,2,3,4,5))
print(t,type(t))

[1 2 3 4 5] <class 'numpy.ndarray'>


# Types of Array
1. 1-D
2. 2-D
3. 3-D

__How to check Dimention__
1. varName.ndimm()

In [8]:
# Dimention
# 0 - in array have only one element it called

arr = np.array(20)
print(arr,type(arr))
print("Dimention :",arr.ndim)

20 <class 'numpy.ndarray'>
Dimention : 0


In [9]:
# 1-d array
arr = np.array([1,2,3,4,5])
print(arr,type(arr))
print("Dimention :",arr.ndim)

[1 2 3 4 5] <class 'numpy.ndarray'>
Dimention : 1


In [13]:
# 2-D Array

arr = np.array([[1, 2, 3], [3, 4, 5]])
print(arr, type(arr))
print("Dimension:", arr.ndim)


[[1 2 3]
 [3 4 5]] <class 'numpy.ndarray'>
Dimension: 2


In [20]:
# 3-D array

arr = np.array([[[1, 2, 3], [3, 4, 5]], [[4, 5, 6], [7, 8, 9]]])
print(arr, type(arr))
print("Dimension:", arr.ndim)


[[[1 2 3]
  [3 4 5]]

 [[4 5 6]
  [7 8 9]]] <class 'numpy.ndarray'>
Dimension: 3


__How to make n Dimention array__

In [15]:
arr = np.array([1,2,3,4],ndmin=6)
print(arr,type(arr))

[[[[[[1 2 3 4]]]]]] <class 'numpy.ndarray'>


_

__How to access Element in all types of array__

In [13]:
# 2-D
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[1, 1]) 

# 3-D
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1, 0, 2]) 
# {Positions: Bracket,row,col}
# Access the element at depth 1, row 0, column 2 (9)

# 4-D
arr = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]])
print(arr[0, 1, 0, 1])  
# {Positions: Block,Bracket,row,col}
# Access depth 0, block 1, row 0, column 1 (6)


5
9
6


# Part-II
1. Slicing of NumPy arrays
2. Functions

In [34]:
# Slicing of NumPy arrays

# 1D
arr = np.array([1,2,3,4,5])
print(arr[0:4])

# 2D
arr = np.array([[(1,2,3),(3,4,5)]])
print(arr[0,1:2])


[1 2 3 4]
[[3 4 5]]


# Data types
1.   i - int
1.   b - bool
1.   u - unsigned int
1.   g - float
1.   c - complex
1.   M - datetime
1.   m - timedelta
1.   O - object
1.   S - string
1.   U - unicode string
1.   V - fixed chunk

In [39]:
# Checking the data type of array
arr = np.array([[(1,2,3),(3,4,5)]])
print(arr.dtype)

arr = np.array(['a','b','c'])
print(arr.dtype)


int32
<U1


In [43]:
# Creating array eith difined data type

arr = np.array([1,2,3], dtype = 'S')
print(arr)
print(arr.dtype)

arr = np.array([1,2,3], dtype = i4') # i4 means -int32
print(arr)
print(arr.dtype)


[b'1' b'2' b'3']
|S1


# NumPy Array shape

In [46]:
# print shape of 
# 2D array
arr = np.array([[1,2,3],[3,4,5]])
print(arr.shape)

# 3D 
arr = np.array([[[1,2,3],[3,4,5],[5,6,7]]])
print(arr.shape)


(2, 3)
(1, 3, 3)


# Joining NumPy Arrays

In [57]:
#1D
a = np.array([1,2,3])
b = np.array([3,4,5])

arr = np.concatenate((a,b))
print(arr)

# 2D
c = np.array([[1,2],[3,4]])
d = np.array([[5,6],[7,8]])

arr = np.concatenate((c,d),axis=0)
print(arr)

[1 2 3 3 4 5]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Spliting Arrays in Parts

In [61]:
arr = np.array([1,2,3,4,5])

# in 2 parts
newArr = np.array_split(arr,2)
print(newArr)

# in 3  Part
newArr = np.array_split(arr,3)
print(newArr)

[array([1, 2, 3]), array([4, 5])]
[array([1, 2]), array([3, 4]), array([5])]


# Ravel & Flatten
Convert Multi-Dimention Array into 1D array

In [71]:
m = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m,"\nDimention is:",m.ndim)

print("-----------")

# Ravel : Convert Multi-Dimention Array into 1D array
n = m.ravel()
print(m,"\nDimention is:",m.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]] 
Dimention is: 3
-----------
[[[1 2 3]
  [4 5 6]
  [7 8 9]]] 
Dimention is: 3


In [75]:
# 4D
c = np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
d = c.ravel()
print(c,"\nDimention is:",d.ndim)


[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]] 
Dimention is: 1


# Unique Function


In [79]:
k = np.array([1,2,3,4,5,3,4,5,5,5,6,6,7,2])
print(k)

# Unique
u = np.unique(k)
print(u)

# Return Index
u = np.unique(k, return_index = True)
print(u)

[1 2 3 4 5 3 4 5 5 5 6 6 7 2]
[1 2 3 4 5 6 7]
(array([1, 2, 3, 4, 5, 6, 7]), array([ 0,  1,  2,  3,  4, 10, 12], dtype=int64))


# Delete


In [81]:
a = np.array([1,2,3,4,5])
d = np.delete(a,[1])
print(d)

[1 3 4 5]


In [83]:
a = np.array([[1,2,3,4,5],[1,6,3,8,9]])
print(a)
d = np.delete(a,1,axis=1)
print(d)

[[1 2 3 4 5]
 [1 6 3 8 9]]
[[1 3 4 5]
 [1 3 8 9]]
